name: altcenter-build

on:
  workflow_call:
    inputs:
      artifact:
        description: "Artifact"
        type: string
        required: true
      architecture:
        description: "Architecture"
        type: string
        required: true

jobs:
  altcenter-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build alterator-browser packages
      run: |
        docker pull --platform linux/${{ inputs.architecture }} \
          ghcr.io/${{ github.repository }}-${{ inputs.architecture }}:latest
        docker run --privileged=true --name alterator-browser-build-${{ inputs.architecture }} -i --log-driver=none \
        -a stdin -a stdout -a stderr -v "$(pwd)":/app --platform linux/${{ inputs.architecture }} \
        ghcr.io/${{ github.repository }}-${{ inputs.architecture }}:latest

    - name: Extract fresh packages
      if: github.ref == 'refs/heads/master'
      run: |
        docker cp alterator-browser-build-${{ inputs.architecture }}:/home/builder2/RPM/RPMS/ "$(pwd)/packages"

    - name: Upload fresh RPM packages
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v3
      with:
        name: alterator-browser-${{ inputs.artifact }}-${{ inputs.architecture }}
        path: ${{ github.workspace }}/packages
